# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cospan Design
email: dave.mccoy@cospandesign.com
description: > # this means to ignore newlines until "baseurl:"
  Designing tools to simplify development and interaction with FPGAs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cospandesign.com" # the base hostname & protocol for your site
twitter_username: cospandesign
github_username:  cospandesign

# Build settings
markdown: kramdown
