# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Writups of Problems or Projects I have solved
email: anonymouse@example.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog where I write about problems I solved. I put things here so I don't need to start out from scratch when I need to do them again.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cospandesign.com" # the base hostname & protocol for your site
twitter_username: cospandesign
github_username:  cospan
future: true

# Build settings
markdown: kramdown
